# name: Deploy Backend to EC2 / Hostinger VPS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to Server via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           # key: ${{ secrets.SSH_PRIVATE_KEY }}
#           password: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: ${{ secrets.SSH_PORT || 22 }}
#           script: |
#             # Navigate to where your project lives on the server
#             cd ${{ secrets.SERVER_PROJECT_PATH }}

#             # Force reset local server changes and pull raw fresh code from GitHub
#             git fetch --all
#             git reset --hard origin/main
#             git pull origin main

#             # Rebuild the Docker environment without downtime
#             docker-compose up --build -d

#             # Clean up old floating docker images to save server disk space
#             docker image prune -f
